made some changes to improve robustness of locking
127.0.0.1 - - [01/Dec/2017 11:36:59] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1997, in __call__
return self.wsgi_app(environ, start_response)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1985, in wsgi_app
response = self.handle_exception(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 273, in error_router
return original_handler(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 270, in error_router
return self.handle_error(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1982, in wsgi_app
response = self.full_dispatch_request()
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 273, in error_router
return original_handler(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 270, in error_router
return self.handle_error(e)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1612, in full_dispatch_request
rv = self.dispatch_request()
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask\app.py",
line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 484, in wrapper
return self.make_response(data, code, headers=headers)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\__init__.py",
line 513, in make_response
resp = self.representations[mediatype](data, *args, **kwargs)
File
"\\tholos.itserv.scss.tcd.ie\ugrad\amhiggin\AppData\Roaming\Python\Python27\site-packages\flask_restful\representations\json.py",
line 21, in output_json
dumped = dumps(data, **settings) + "\n"
File "C:\Python27\lib\json\__init__.py", line 250, in dumps
sort_keys=sort_keys, **kw).encode(obj)
File "C:\Python27\lib\json\encoder.py", line 209, in encode
chunks = list(chunks)
File "C:\Python27\lib\json\encoder.py", line 434, in _iterencode
for chunk in _iterencode_dict(o, _current_indent_level):
File "C:\Python27\lib\json\encoder.py", line 390, in _iterencode_dict
yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 9:
invalid start byte